CC=g++
CFLAGS=-c -Wall -std=c++11
NLTMX=C:/Users/fuerchter/Downloads/NLTmxMap
SFML=C:/Users/fuerchter/Downloads/FULLSFML3
SFGUI=C:/Users/fuerchter/Downloads/SFGUI
RAPIDXML=C:/Users/fuerchter/Downloads/rapidxml-1.13/rapidxml-1.13

all : main.o Level.o Map.o Wave.o Enemy.o
	$(CC) main.o Level.o Map.o Wave.o Enemy.o -L$(SFML)/lib -lsfml-graphics -lsfml-window -lsfml-system -lsfml-audio -L$(SFGUI)/lib -lsfgui -L$(NLTMX) -lNLTmxMap
	
main.o : main.cpp Level.h Level.cpp
	$(CC) $(CFLAGS) main.cpp -I$(SFML)/include -I$(NLTMX) -I$(RAPIDXML)

Level.o : Level.h Level.cpp Map.h Map.cpp Wave.h Wave.cpp
	$(CC) $(CFLAGS) Level.cpp -I$(SFML)/include -I$(NLTMX) -I$(RAPIDXML)
	
Map.o : Map.h Map.cpp
	$(CC) $(CFLAGS) Map.cpp -I$(SFML)/include -I$(NLTMX)
	
Wave.o : Wave.h Wave.cpp Enemy.h Enemy.cpp
	$(CC) $(CFLAGS) Wave.cpp -I$(SFML)/include
	
Enemy.o : Enemy.h Enemy.cpp
	$(CC) $(CFLAGS) Enemy.cpp -I$(SFML)/include